# Generated by Django 5.0.3 on 2024-04-02 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiwako', '0002_wiwako_agwera_wiwako_maragshia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='carousel/')),
                ('wiwako', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiwako.wiwako')),
            ],
        ),
    ]
