# Generated by Django 5.0.3 on 2024-04-02 19:03

import carousel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='photo',
            field=models.ImageField(upload_to=carousel.models.carousel_photo_path),
        ),
    ]
