# Generated by Django 5.0.3 on 2024-04-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiwako', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiwako',
            name='agwera',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wiwako',
            name='maragshia',
            field=models.BooleanField(default=True),
        ),
    ]
